name: "update"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:

  update_bot:
    name: Update sarufi bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Adding Ansible Variables
        run: |
          cat << EOF > .env
          ---
          CLIENT_ID: "${{ secrets.CLIENT_ID }}"
          CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
          BOT_ID: "${{ secrets.BOT_ID }}"
          EOF

      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
      - run: |
          pip install -r requirements.txt
          python create-bot.py
          
